[package]
name = "omega"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
smallvec = "1.15.1"
crossbeam = "0.8.4"
dashmap = "7.0.0-rc2"
twox-hash = "2.1.2"
fastrand = "2.3.0"

[dev-dependencies]
fake = "4.4.0"
